### ISSUE TITLE
Support VSCode multi-root

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dev-cycles/contextive#38]
Think about having a monorepo and a multi root workspace where every package/app has a root also and maybe the monorepo as well.

**Comment by chrissimon-au** [comment]
Thanks for the suggestion! Yes, there are a few changes needed to support multi-root, but it shouldn't be too difficult to add support.

To confirm, since this is a monorepo, would you be ok with having a single contextive definitions file in the monorepo?

I'll need to do some experiments to confirm, but I think each package's vscode workspace root would need it's own `.vscode/settings.json` file which would contain a `contextive.path` definition with a relative path back to the root of the repository pointing at that same definitions file, e.g. assuming your package is in `src/packages/package-a`, you'd need a file `src/packages/pakage-a/.vscode/settings.json` which would contain a `contextive.path` key with a value of `../../../.contextive/definitions.yml`.

Would that be ok?  If so, I'll do a spike shortly to confirm and then start looking at adding this support.

**Comment by sschneider-ihre-pvs** [comment]
sure, a single file is enough. I am also not sure where the path to the file should be looked up since in a multi root worksspace you may have totally different folder. In my case I have the base project and each app, but that could be some special case.

**Comment by sschneider-ihre-pvs** [comment]
Usually, a single monorepo belongs to the same domain. So it often represents just different bounded contexts of the same domain.

**Comment by chrissimon-au** [comment]
> I am also not sure where the path to the file should be looked up since in a multi root worksspace you may have totally different folder.

Yes, this is the central challenge.  There is some guidance here - https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#language-settings.  It provides some hints for our scenario, but is more related to when each root in the workspace may have a different definitions file, using 'resource-scoped' settings.

For the single-file scenario in the monorepo, I think it would make more sense to define the setting in the [.code-workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings) file itself.  The value should be relative to the location of that `.code-workspace` file. In the vscode extension, we can leverage the [workspaces.workspaceFile](https://code.visualstudio.com/api/references/vscode-api#workspace.workspaceFile) VsCode API to find the location of that `.code-workspace` file and resolve the definitions file location relative to it.  Then utilise 'middleware' approach outlined [in the guidance linked above](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#language-settings) to resolve the absolute path to the definitions file in the client and ensure the server only receives the absolute path to that file, no matter which workspace you are working in.

This would also be compatible with a future mode where we do support separate definitions files per root, as those separate roots can each have their own `.vscode/settings.json` file defining the location of the definitions file for that root, and we can use resource-scoped settings to isolate the values, which would be resolved against the root path of the relevant workspace, following the pattern outlined in that guidance link above. The reason we won't support that immediately is that it will also need the language server component to be further updated to support loading multiple definition files at the same time and looking up the correct definitions file depending on the file currently being worked on.

**Comment by chrissimon-au** [comment]
Hi @sschneider-ihre-pvs, this is now working in v1.7.0 - give it a try and let me know if it suits.  There is a description of how to ensure the configuration is correct here: https://github.com/dev-cycles/contextive/blob/main/src/vscode/contextive/README.md#multiple-bounded-contexts-multi-root-shared-definitions-file

If you'd like it to do anything differently, please create a new issue for that change.

Thanks again for the suggestion, I hope it's helpful!
