### ISSUE TITLE
Problem running contextive

### ISSUE THREAD

**Issue by pdjota** [dev-cycles/contextive#48]
Hello team,
I installed Contextive and when trying to hover over a term in the definition file I get:
`Request textDocument/hover failed.`

VSCode: July 2023 (version 1.81)
Contextive: v1.9.3
macOS: 13.4 (22F66)

Output and sample definition.yml
https://gist.github.com/pdjota/3a41ba0e484babac0d60228979791823

**Comment by chrissimon-au** [comment]
Hi @pdjota, while I assume that the empty terms list is a temporary state, I have pushed v1.9.4 today that improves the resilience so that one context having an empty terms list doesn't break it for terms defined in other contexts.

Thanks again, and please feel free to raise another issue if you have any further problems!
