### ISSUE TITLE
Add a `LICENSE` file

### ISSUE THREAD

**Issue by erikjuhani** [dev-cycles/contextive#52]
I noticed that there's no `LICENSE` file specified, even though there is a mention of the `MIT` license in the root `README`. This might be confusing for someone who is trying to determine the project's licensing, potentially leading to misinterpretations.

According to GitHub's documentation on licenses, it's considered best practice to include a license file with the project.
> As a best practice, we encourage you to include the license file with your project.
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Should a `LICENSE` file be added into this project?

**Comment by chrissimon-au** [comment]
Hi @erikjuhani - good point.  As well as being noted in the footer of the README.md with a link to the MIT license page, a LICENSE file is included in the vscode extension so that it can be referenced from the vscode extension marketplace, but you're right, it would be better to be explicit and include an explicit LICENSE file in the root of the repo.  I've corrected this now, thanks for pointing it out!

**Comment by erikjuhani** [comment]
> Hi @erikjuhani - good point. As well as being noted in the footer of the README.md with a link to the MIT license page, a LICENSE file is included in the vscode extension so that it can be referenced from the vscode extension marketplace, but you're right, it would be better to be explicit and include an explicit LICENSE file in the root of the repo. I've corrected this now, thanks for pointing it out!

Ah I didn't notice there was one in the VSCode extension! Anyway great that it's now included in the root. It also makes it nicely show in the Github UI too! 😄
