### ISSUE TITLE
Schema for definitions.yml file

### ISSUE THREAD

**Issue by FH-Inway** [dev-cycles/contextive#74]
**Is your feature request related to a problem? Please describe.**
When editing the definitions.yml file for Contextive, it is unclear what the structure and available keywords are. 
When consuming a definitions.yml file, validation is done by [Definitions.fs](https://github.com/dev-cycles/contextive/blob/main/src/core/Contextive.Core/Definitions.fs). If there are errors in the file, the validation fails with a "Definitions file is empty." error message.

**Describe the solution you'd like**
When editing the definitions.yml file for Contextive, editors with support for schemas should be able to be set up so a schema can be used. This would improve the editing experience by providing intellisense and validation while editing. See the screenshot in the "Additional context" section for an example of how this looks like in Visual Studio Code with the [Red Hat YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml).

When consuming a definitions.yml file, it could be validated against a schema. In case of errors, more targeted error messages could be provided. It would also allow validation by third party consumers.

**Describe alternatives you've considered**
No alternatives have been considered so far.

**Additional context**

![image](https://github.com/user-attachments/assets/e5d6d45c-9d09-49c6-9f8d-b8c6d8c84748)

**Comment by FH-Inway** [comment]
As you can tell from the screenshot, I wrote a first draft of the schema in https://github.com/FH-Inway/contextive/commit/cb0e5e5f045f76d2015bbf0ff65667ccac05cff9

To use it, add the following line to the definitions.yml file:
`# yaml-language-server: $schema=contextive-schema.json`
The `contextive-schema.json` part is the name of the schema file. It could also include a full or relative path or be a URL.

[How to configure YAML schema to make editing files easier](https://developers.redhat.com/blog/2020/11/25/how-to-configure-yaml-schema-to-make-editing-files-easier) describes additional options how the schema can be made available. Using www.schemastore.org would be the most convenient option for the users, but would require a change in the naming schema of the file (e.g. `definitions.contextive.yml`).

**Comment by chrissimon-au** [comment]
Thanks @FH-Inway - this looks great!

Because of the need to update the file name, I think for now the simplest thing would be to update the [initialize definitions custom operation](https://github.com/dev-cycles/contextive/blob/main/src/language-server/Contextive.LanguageServer/DefinitionsInitializer.fs) to dump the schema file next to the definitions file and update the default definitions file to have the required header (and include other comments to guide people to documentation to install the right extension).

Regarding the use of schemastore - in a comment on [#54](https://github.com/dev-cycles/contextive/issues/54#issuecomment-1807515740) I was exploring some potential future changes to the configuration approach.

I've had some further thoughts since then, but they build on that comment, the general idea is:

* Put each context in its own file (no longer offer a list of contexts), and to locate that file in the root folder of the context (not in a 'hidden' `.contextive` folder).
* If a folder references multiple contexts, then allow the file to nominate to _import_ a set of definitions from a location.  This could be a relative path, absolute path, or even a url (which would support some of the scenarios explored in #71 

Since this would be a major breaking change, we have the opportunity to rename the file at that time and could look at adding it to schema store then.

**Comment by chrissimon-au** [comment]
Separate note - current behaviour is supposed to include a warning popup (and log) with a detailed error message about the failure including line and column...

There are a bunch of [unit tests](https://github.com/dev-cycles/contextive/blob/89f94f4d8e5013f1de83d5e3c4dae363a527820a/src/core/Contextive.Core.Tests/DefinitionsTests.fs#L280) for this behaviour, so if it's only giving "file is empty" errors there might be an issue integration bug somewhere...

**Comment by FH-Inway** [comment]
You are right, in some cases I get the warning popup with line and column numbers. Not quite sure how I got the "file is empty" error, will make sure to document repro steps next time I get it.

That said, a file that is accepted by Definitions.fs can still have errors and produce an ugly error message like in the screenshot. As the red squiggles indicate, the schema would have caught that.

![image](https://github.com/user-attachments/assets/3f25efe2-22c2-40f5-8be5-750cd4f28259)

**Comment by chrissimon-au** [comment]
Yes, that's a great example of where the file is parsable (valid yml), but not valid for contextive. While the schema definition helps for IDE tools, I feel like I should also take a look at validating against a schema in the language-server too, for cross-IDE support, and probably more helpful error messages than the parser error message.

Thanks again for putting this together!

I'll take a look at adding it in two stages:

1. Update the initializer:
   1. dump the schema file next to the initialized definitions file
   2. update the initialized definitions file to reference the adjacent schema
   3. update documentation to guide folk to download the schema and how to use it/update existing defnitions files
2. Add a language-server schema validator using the schema

Later, when I look at #54 we'll update the file naming convention to support using schemastore as well.

**Comment by chrissimon-au** [comment]
Also added some backend validation [here](https://github.com/dev-cycles/contextive/commit/0fb0978640f594843d1f8ff25959ea3d0bf729ae) which addresses the specific case @FH-Inway found - an undefined term name.  All other fields are optional, so there is no other validation required at this point.

Further work to support auto-complete in the file will be done on future tickets, e.g. #54

**Comment by chrissimon-au** [comment]
Released on [v1.12.0](https://github.com/dev-cycles/contextive/releases/tag/v1.12.0)

**Comment by chrissimon-au** [comment]
Now that #54 is merged, have contributed a schema to json schema store.  This will ensure access to the schema validation no matter where the glossary files are located: https://github.com/SchemaStore/schemastore/pull/4580
